name: Check compile

on:
  push:
    branches:
      - main
    paths-ignore:
      - "LICENSE"
      - ".vscode/settings.json"
      - "**/*.{md,jpg,jpeg,png,ico,svg,mp4}"

  pull_request:
    branches:
      - main
    paths-ignore:
      - "LICENSE"
      - ".vscode/settings.json"
      - "**/*.{md,jpg,jpeg,png,ico,svg,mp4}"

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TURBO_REMOTE_ONLY: true

jobs:
  check-compile-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      # install bun
      - uses: oven-sh/setup-bun@v1

      # install rust
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
          toolchain: nightly

      - name: Install bun dependencies
        run: bun install

      - name: Check if project compiles
        run: bun run build

      - name: Archive compiled for windows
        uses: actions/upload-artifact@v4
        with:
          name: windows-compiled
          path: apps/desktop/core/target/release/*/

  check-compile-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # install bun
      - uses: oven-sh/setup-bun@v1

      # install rust
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
          toolchain: nightly

      - run: sudo apt-get update

      - name: Install Tauri prerequisites
        run: sudo apt-get install libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Install bun dependencies
        run: bun install

      - name: Check if project compiles
        run: bun run build

      - name: Archive compiled for ubuntu
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-compiled
          path: apps/desktop/core/target/release/*/

  check-compile-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      # install bun
      - uses: oven-sh/setup-bun@v1

      # install rust
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
          toolchain: nightly

      - name: Install bun dependencies
        run: bun install

      - name: Check if project compiles
        run: bun run build

      - name: Archive compiled for macos
        uses: actions/upload-artifact@v4
        with:
          name: macos-compiled
          path: apps/desktop/core/target/release/*/
