name: Check desktop compile

on:
  push:
    branches:
      - main
    paths:
      - "apps/desktop/**"
      - ".github/workflows/ci-check-compile-desktop.yaml"

  pull_request:
    branches:
      - main
    paths:
      - "apps/desktop/**"
      - ".github/workflows/ci-check-compile-desktop.yaml"

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TURBO_REMOTE_ONLY: true

jobs:
  check-compile-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      # install bun
      - uses: oven-sh/setup-bun@v1

      # install rust
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
          toolchain: nightly

      - name: Install bun dependencies
        run: bun install

      - name: Check if project compiles
        run: bunx turbo run build --filter=td-ollama-desktop

      - name: Archive compiled for windows
        uses: actions/upload-artifact@v4
        with:
          name: windows-compiled-msi-nsis
          path: apps/desktop/core/target/release/bundle/**/*

  check-compile-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # install bun
      - uses: oven-sh/setup-bun@v1

      # install rust
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
          toolchain: nightly

      - run: sudo apt-get update

      - name: Install Tauri prerequisites
        run: sudo apt-get install libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Install bun dependencies
        run: bun install

      - name: Check if project compiles
        run: bunx turbo run build --filter=td-ollama-desktop

      - name: Archive compiled for linux
        uses: actions/upload-artifact@v4
        with:
          name: linux-compiled-rpm-deb
          path: |
            apps/desktop/core/target/release/bundle/**/*
            !apps/desktop/core/target/release/bundle/appimage

  check-compile-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      # install bun
      - uses: oven-sh/setup-bun@v1

      # install rust
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
          toolchain: nightly

      - name: Install bun dependencies
        run: bun install

      - name: Install macos target
        run: rustup target add x86_64-apple-darwin

      - name: Check if project compiles
        run: bunx turbo run build --filter=td-ollama-desktop -- --target=x86_64-apple-darwin

      - name: Archive compiled for macos
        uses: actions/upload-artifact@v4
        with:
          name: macos-compiled-app-dmg
          path: apps/desktop/core/target/x86_64-apple-darwin/release/bundle/**/*
