name: Check linting

on:
  push:
    branches:
      - main
    paths:
      - "apps/**"
      - ".github/workflows/ci-check-linting.yaml"
      - "turbo.json"

  pull_request:
    branches:
      - main
    paths:
      - "apps/**"
      - ".github/workflows/ci-check-linting.yaml"
      - "turbo.json"

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TURBO_REMOTE_ONLY: true

jobs:
  check-linting:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      # install bun
      - uses: oven-sh/setup-bun@v1

      # install rust
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt
          toolchain: nightly

      - name: Install bun dependencies
        run: bun install

      - name: Check project linting
        run: bun lint
