name: Check linting

on:
  push:
    branches:
      - main
    paths-ignore:
      - "LICENSE"
      - ".vscode/settings.json"
      - "**/*.{md,jpg,jpeg,png,ico,svg,mp4}"

  pull_request:
    branches:
      - main
    paths-ignore:
      - "LICENSE"
      - ".vscode/settings.json"
      - "**/*.{md,jpg,jpeg,png,ico,svg,mp4}"

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TURBO_REMOTE_ONLY: true

jobs:
  check-linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # install bun
      - uses: oven-sh/setup-bun@v1

      # install rust
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
          toolchain: nightly

      - name: Install bun dependencies
        run: bun install

      - name: Check project linting
        run: bun lint
